trigger:
- master
- master-next
- dunfell

schedules:
- cron: "0 12 * * *"
  displayName: Daily build
  branches:
    include:
    - master
    - dunfell
  always: true

jobs:
  - template: templates/build.yml
    parameters:
      pool:
        vmImage: 'ubuntu-20.04'
      buildtype: 'freertos'
      machine: 'qemuarmv5'

  - template: templates/build.yml
    parameters:
      pool:
        vmImage: 'ubuntu-20.04'
      buildtype: 'poky'
      machine: 'qemuarmv5'
